// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get my academic profile",
  description: "Get the signed-in student's UniGenius profile: display name, department, current semester, roll number and Pro status.",
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("display_name, department, current_semester, roll_number, section, university, is_pro, headline, skills").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) throw new ToolError(error.message);
    if (!data) throw new ToolError("No profile found for this account.");
    const profile = {
      displayName: data.display_name ?? null,
      department: data.department ?? null,
      currentSemester: data.current_semester ?? null,
      rollNumber: data.roll_number ?? null,
      section: data.section ?? null,
      university: data.university ?? null,
      isPro: Boolean(data.is_pro),
      headline: data.headline ?? null,
      skills: (data.skills ?? []).map((s) => s)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/tools/get-attendance.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.0";
import { z } from "npm:zod@^3.25.76";
var get_attendance_default = defineTool2({
  name: "get_attendance_summary",
  title: "Get attendance summary",
  description: "Summarise the signed-in student's attendance per subject (present, absent, percentage) for a semester, with the most recent records.",
  inputSchema: {
    semester: z.number().int().describe("Semester number to summarise. Omit for all semesters.").optional(),
    subject: z.string().describe("Filter to a single subject name.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ semester, subject }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("attendance").select("subject, status, date, semester").eq("user_id", ctx.getUserId()).order("date", { ascending: false }).limit(500);
    if (typeof semester === "number") query = query.eq("semester", semester);
    if (subject) query = query.eq("subject", subject);
    const { data, error } = await query;
    if (error) throw new ToolError2(error.message);
    const bySubject = /* @__PURE__ */ new Map();
    for (const row of data ?? []) {
      const entry = bySubject.get(row.subject) ?? { subject: row.subject, present: 0, absent: 0, total: 0 };
      entry.total += 1;
      if (row.status === "present") entry.present += 1;
      else entry.absent += 1;
      bySubject.set(row.subject, entry);
    }
    const subjects = [...bySubject.values()].map((e) => ({
      ...e,
      percentage: e.total ? Math.round(e.present / e.total * 1e3) / 10 : 0,
      belowThreshold: e.total ? e.present / e.total < 0.75 : false
    }));
    const recent = (data ?? []).slice(0, 20).map((r) => ({
      subject: r.subject,
      status: r.status,
      date: r.date,
      semester: r.semester
    }));
    return {
      content: [{ type: "text", text: JSON.stringify({ subjects, recent }, null, 2) }],
      structuredContent: { subjects, recent }
    };
  }
});

// src/lib/mcp/tools/list-study-materials.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@3.0.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_study_materials_default = defineTool3({
  name: "list_study_materials",
  title: "List study materials",
  description: "List teacher-uploaded study materials available to the signed-in student, optionally filtered by subject or semester.",
  inputSchema: {
    subject: z2.string().describe("Filter by subject name.").optional(),
    semester: z2.number().int().describe("Filter by semester number.").optional(),
    limit: z2.number().int().describe("Maximum number of materials to return (default 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ subject, semester, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("study_materials").select("id, title, description, subject, semester, file_name, file_url, created_at").order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 20, 1), 100));
    if (subject) query = query.eq("subject", subject);
    if (typeof semester === "number") query = query.eq("semester", semester);
    const { data, error } = await query;
    if (error) throw new ToolError3(error.message);
    const materials = (data ?? []).map((m) => ({
      id: m.id,
      title: m.title,
      description: m.description ?? null,
      subject: m.subject,
      semester: m.semester ?? null,
      fileName: m.file_name,
      fileUrl: m.file_url,
      createdAt: m.created_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(materials, null, 2) }],
      structuredContent: { materials }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-exams.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@3.0.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_upcoming_exams_default = defineTool4({
  name: "list_upcoming_exams",
  title: "List upcoming exams",
  description: "List upcoming exams from the university exam schedule, optionally filtered by semester.",
  inputSchema: {
    semester: z3.number().int().describe("Filter by semester number.").optional(),
    limit: z3.number().int().describe("Maximum number of exams to return (default 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ semester, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    let query = supabase.from("exam_schedule").select("id, subject, exam_type, exam_date, semester").gte("exam_date", today).order("exam_date", { ascending: true }).limit(Math.min(Math.max(limit ?? 20, 1), 100));
    if (typeof semester === "number") query = query.eq("semester", semester);
    const { data, error } = await query;
    if (error) throw new ToolError4(error.message);
    const exams = (data ?? []).map((e) => ({
      id: e.id,
      subject: e.subject,
      examType: e.exam_type,
      examDate: e.exam_date,
      semester: e.semester
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(exams, null, 2) }],
      structuredContent: { exams }
    };
  }
});

// src/lib/mcp/tools/get-study-plan.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@3.0.0";
var get_study_plan_default = defineTool5({
  name: "get_study_plan",
  title: "Get my study plan",
  description: "Get the signed-in student's latest generated weekly study plan, including subjects, weekly hours and schedule.",
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError5("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("study_plans").select("id, semester, subjects, weekly_hours, exam_date, schedule, updated_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(1).maybeSingle();
    if (error) throw new ToolError5(error.message);
    if (!data) {
      return { content: [{ type: "text", text: "No study plan has been generated yet." }] };
    }
    const plan = {
      id: data.id,
      semester: data.semester,
      subjects: (data.subjects ?? []).map((s) => s),
      weeklyHours: data.weekly_hours,
      examDate: data.exam_date ?? null,
      schedule: data.schedule ?? null,
      updatedAt: data.updated_at
    };
    return {
      content: [{ type: "text", text: JSON.stringify(plan, null, 2) }],
      structuredContent: { plan }
    };
  }
});

// src/lib/mcp/tools/log-study-session.ts
import { defineTool as defineTool6, ToolError as ToolError6 } from "npm:@lovable.dev/mcp-js@3.0.0";
import { z as z4 } from "npm:zod@^3.25.76";
var log_study_session_default = defineTool6({
  name: "log_study_session",
  title: "Log a study session",
  description: "Record a completed study session for the signed-in student so it counts toward progress tracking.",
  inputSchema: {
    subject: z4.string().describe("Subject that was studied."),
    durationMinutes: z4.number().int().describe("How long the session lasted, in minutes."),
    notes: z4.string().describe("Optional notes about what was covered.").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ subject, durationMinutes, notes }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError6("Not authenticated");
    const trimmed = subject.trim();
    if (!trimmed) throw new ToolError6("subject must not be empty");
    if (durationMinutes <= 0 || durationMinutes > 1440) {
      throw new ToolError6("durationMinutes must be between 1 and 1440");
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("study_sessions").insert({
      user_id: ctx.getUserId(),
      subject: trimmed,
      duration_minutes: durationMinutes,
      notes: notes?.trim() || null
    }).select("id, subject, duration_minutes, notes, studied_at").single();
    if (error) throw new ToolError6(error.message);
    const session = {
      id: data.id,
      subject: data.subject,
      durationMinutes: data.duration_minutes,
      notes: data.notes ?? null,
      studiedAt: data.studied_at
    };
    return {
      content: [{ type: "text", text: `Logged ${session.durationMinutes} minutes of ${session.subject}.` }],
      structuredContent: { session }
    };
  }
});

// src/lib/mcp/tools/list-flashcard-sets.ts
import { defineTool as defineTool7, ToolError as ToolError7 } from "npm:@lovable.dev/mcp-js@3.0.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_flashcard_sets_default = defineTool7({
  name: "list_flashcard_sets",
  title: "List my flashcard sets",
  description: "List the signed-in student's saved flashcard sets, with card counts and optionally the cards themselves.",
  inputSchema: {
    subject: z5.string().describe("Filter by subject name.").optional(),
    includeCards: z5.boolean().describe("Include the cards of each set (default false).").optional(),
    limit: z5.number().int().describe("Maximum number of sets to return (default 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ subject, includeCards, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError7("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("flashcard_sets").select("id, title, subject, semester, source_type, cards, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 20, 1), 50));
    if (subject) query = query.eq("subject", subject);
    const { data, error } = await query;
    if (error) throw new ToolError7(error.message);
    const sets = (data ?? []).map((s) => {
      const cards = Array.isArray(s.cards) ? s.cards : [];
      return {
        id: s.id,
        title: s.title,
        subject: s.subject,
        semester: s.semester,
        sourceType: s.source_type,
        cardCount: cards.length,
        createdAt: s.created_at,
        cards: includeCards ? cards.map((c) => {
          const card = c ?? {};
          return {
            front: typeof card.front === "string" ? card.front : String(card.question ?? ""),
            back: typeof card.back === "string" ? card.back : String(card.answer ?? "")
          };
        }) : []
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(sets, null, 2) }],
      structuredContent: { sets }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tvazcfwsnjjbwvzvxghx";
var mcp_default = defineMcp({
  name: "unigenius-ai",
  title: "UniGenius AI",
  version: "0.1.0",
  instructions: "Tools for UniGenius AI, a study assistant for university software-engineering students. Read the signed-in student's academic profile, attendance, study plan, flashcard sets, teacher-uploaded study materials and upcoming exams, and log completed study sessions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_profile_default,
    get_attendance_default,
    get_study_plan_default,
    list_flashcard_sets_default,
    list_study_materials_default,
    list_upcoming_exams_default,
    log_study_session_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
